name: star_wars_estimation
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          python3 -m venv .
          source bin/activate
          pip install -r requirements.txt
          python give-me-the-odds.py millennium-falcon.json examples/example1/empire.json
          python give-me-the-odds.py millennium-falcon.json examples/example2/empire.json
          python give-me-the-odds.py millennium-falcon.json examples/example3/empire.json
          python give-me-the-odds.py millennium-falcon.json examples/example4/empire.json

          dist/give-me-the-odds millennium-falcon.json examples/example1/empire.json
          dist/give-me-the-odds millennium-falcon.json examples/example2/empire.json
          dist/give-me-the-odds millennium-falcon.json examples/example3/empire.json
          dist/give-me-the-odds millennium-falcon.json examples/example4/empire.json
